name: CI Workflow

on:
  push:
    branches:
      - main
      - '**'  # This triggers on all branches
  pull_request:
    branches:
      - main  # This triggers when a PR targets the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a script
        run: echo "Build triggered on branch ${{ github.ref }}"
