name: Hello GitHub Actions

on:
  push:
  workflow_dispatch:
    

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello, GitHub Actions!"
